server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ott}
    username: ${SPRING_DATASOURCE_USERNAME:ott}
    password: ${SPRING_DATASOURCE_PASSWORD:ottpw}

  # flyway 설정
  flyway:
    enabled: false

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    #배포 할 때는 open-in-view false 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:}
    presign-expire-seconds: ${AWS_S3_PRESIGN_EXPIRE_SECONDS:900}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
